"""

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""

def fib(n):
    if n == 1:
        return 1
    elif n == 2:
        return 2
    else:
        return fib(n-1) + fib(n-2)
        
def solveit():
    s = 0
    i = 1
    stop = True
    while stop:
        n = fib(i)
        if n > 4000000:
            stop = False
        elif n % 2 == 0:
            s += n
        i += 1
    print(s)
    
def neater():
    s = 0
    i = 1
    j = 1
    while j < 4000000:
        if j % 2 == 0:
            s += j
        j = fib(i)
        i += 1
    print(s)
